### ISSUE TITLE
Background color same as text color in active state on small, secondary buttons

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#102]
## Describe the bug
When you click on a button that is using the `.button--small .button--secondary` modifiers putting it into the `:active` state, the text color and the background color are the same making the text unreadable.

## Expected behavior
Button text should be readable and meet color contrast standards

## Relevant context (required)
- Happening because of an extra `background-color` [property on this line](https://github.com/indiana-university/rivet-source/blob/develop/src/sass/components/_buttons.scss#L206).

## Steps to reproduce
Click and hold on small, secondary button variant.

**Comment by illusivesunrae** [comment]
Merged into master with #110.
