### ISSUE TITLE
Scroll bar disappears

### ISSUE THREAD

**Issue by ashleydbush** [indiana-university/rivet-source#106]
## Describe the bug
We are displaying content in a collapsible format.  When all levels are initially expanded the scroll bar appears and works as expected.  However, if data is deleted from one of the levels and then everything is collapsed again, the scroll bar is missing.

## Expected behavior
We expect the scroll bar to remain as data is added/deleted.

## Relevant context (required)
- The issue appears on the queues page of the FireForm application
    - https://qa-fireform-qa.eas.iu.edu/admin/queues
    - contact ashbush@iu.edu or tdlewis@iu.edu for access
- The browsers in which you encountered the bug, if applicable.
   - FireFox
   - Chrome
   - IE
   - Edge
[Missing scroll bar.docx](https://github.com/indiana-university/rivet-source/files/3063696/Missing.scroll.bar.docx)

**Comment by levimcg** [comment]
@ashleydbush Thank you for opening this issue! We've pulled it into the backlog and are looking into it. We'll reach out if we have anymore questions.

**Comment by illusivesunrae** [comment]
I contacted the team, and the issue is no longer reproducible.
