### ISSUE TITLE
Background scrolls when drawer is open

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#11]
When the drawer is open on smaller screens and an users try to scroll to all of the drawer's contents, the background scrolls instead of the drawer.

I think this may have something to do with the way the drawers height is determined by how much content is inside of it (menu options, etc.) instead of being set to the full height of the document.

I've only seen this on windows devices and have not been able to recreate it on iOS/macOS devices so I'll need to do some testing on windows to get some screenshots.

**Comment by zttodd** [comment]
We will be redesigning the drawer in future versions of Rivet. Closing this issue.
