### ISSUE TITLE
Focus styling issue on input groups

### ISSUE THREAD

**Issue by thrclark** [indiana-university/rivet-source#111]
There's a focus styling issue on input groups that becomes very apparent when the secondary button style is applied:

![Screen Shot 2019-05-14 at 3 02 08 PM](https://user-images.githubusercontent.com/5652113/57726858-0ededa00-765e-11e9-9fd2-7f52f0ed11b9.png)

We were able to hack around it with this:

`.rvt-input-group__input:focus:not(:last-child) {
	z-index: 201;
}`

But there's probably a better way to integrate a solution within the .scss structure.

**Comment by levimcg** [comment]
@thrclark Thanks for opening this. This seems like a good update to make. We've pulled it into the backlog. 👍

**Comment by illusivesunrae** [comment]
Released in PR #140.
