### ISSUE TITLE
Replace instances of bp() with breakpoint variable

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#115]
The `bp()` Sass function has been deprecated in favor of the `$breakpoint-*` variables. Replace all remaining instances of `bp()` with the variable.

See the discussion on the [menu component pull request](https://github.com/indiana-university/rivet-source/pull/113) where this came up.

**Comment by levimcg** [comment]
Real quick. When we talked I meant that we should replace the `bp()` sass function with breakpoint variables instead. I still find the `mq()` _mixin_ pretty useful. 

Here's the function I was talking about:

https://github.com/indiana-university/rivet-source/blob/develop/src/sass/core/_tools.scss#L12

**Comment by scottanthonymurray** [comment]
Aha, just realized that looking through the source. Thanks for catching that!

**Comment by illusivesunrae** [comment]
Pulled into master with PR #117.
