### ISSUE TITLE
Focus issue with SVG for IE 11 browser

### ISSUE THREAD

**Issue by aitiu** [indiana-university/rivet-source#122]
IE 11 has focusable as default for SVG, Please add attribute focusable="false" to SVG icons

eg.
<svg aria-hidden="true" focusable="false" ...

**Comment by zttodd** [comment]
Based on your description, it sounds like this issue is specific to the browser in question (IE11). Even though this is an issue with your project, it's a browser-specific optimization that you can adjust individually for your use case.
