### ISSUE TITLE
Missing banner on minified CSS

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#124]
I noticed that the copyright/version banner is missing on the compiled and minified version of the CSS (`rivet.min.css`) that we're shipping.

Seems like the banner task for minified CSS must have got lost in the shuffle when we refactored everything to Gulp 4.

## Relevant context (required)
- See the hosted css file here with no banner: https://assets.uits.iu.edu/css/rivet/1.6.0/rivet.min.css

**Comment by illusivesunrae** [comment]
Released in PR #140.
