### ISSUE TITLE
Reverse-tabbing on new modal window

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#13]
When a modal is opened, focus should shift to it and tab path should be contained within the elements of that modal; and this is the way that Rivel modal behaves when you forward-tab after opening. Howvever, if you reverse-tab after opening the modal. it will cause the focus to jump out of the modal and on to the page below. See the attached screenshot where the focus has been moved to the main screen (highlighted in yellow).

![screenshot_2](https://media.github.iu.edu/user/4398/files/0ae32f88-cbea-11e8-9f1e-e07247e28b17)

**Comment by illusivesunrae** [comment]
Merged into master in PR #207.
