### ISSUE TITLE
Secondary buttons (and some other components) should have white background

### ISSUE THREAD

**Issue by basham** [indiana-university/rivet-source#130]
It seems as if the aesthetic intention behind several Rivet components is to have them rest on white backgrounds. However, sometimes these things are on colored backgrounds, even if a light gray. But there's nothing preventing them from even being on darker backgrounds or even other hues (if it would serve a good purpose). It seems like a number of components would benefit from white backgrounds, instead of transparent backgrounds:

- Secondary buttons: `.rvt-button--secondary`
- Secondary badges: `.rvt-badge--secondary`, etc.
- Inputs: `input[type]`
- Pagination: `.rvt-pagination__item`

There may be other cases, but these ones stand out to me.

**Comment by illusivesunrae** [comment]
We have decided to close this issue. The background color for these items is currently set to inherit, which may be some developers' preference. We may consider adding further documentation in the future to clarify that developers are responsible for determining and fixing issues related to contrast when placing such elements on non-white backgrounds.
