### ISSUE TITLE
Dropdown arrow keys aren't being captured causing page to jump

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#136]
https://rivet.iu.edu/components/navigation/dropdown/ As an example open a dropdown and use the down arrow and notice the page jumps.

**Comment by jolamar** [comment]
This seems to be related to event.preventDefault in this commit (which was removed):
https://github.com/indiana-university/rivet-source/commit/7c50cf373eeabe99a9a0efe367eaf143f24fcac1#diff-c21c78863bc58f6e03837c5c7788f148

**Comment by zttodd** [comment]
Released with PR #294.
