### ISSUE TITLE
Incorrect sizing on <input type="search">

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#14]
I would expect `<input>` elements with `type="text"` to look the same as those with `type="search"`, but it appears there are differences between the two, mostly in sizing. This causes particular issues with using a `<input type="search">` inside of a `rvt-input-group`.

You can see the issue illustrated in this codepen https://codepen.io/ohnoitsaustin/pen/PymPbe

this issue _seems_ to stem from the following CSS rule in Rivet:

```
input[type=search] {
    box-sizing: content-box;
}
```

I'm not sure if this is part of the normalizing CSS, but the result is that search inputs are sized differently than other text inputs.

**Comment by levimcg** [comment]
This was fixed in the the 1.2.0 release. Closing.
