### ISSUE TITLE
rvt-table-stripes background color not visible in some monitor resolution

### ISSUE THREAD

**Issue by aitiu** [indiana-university/rivet-source#141]
.table-stripes tr:nth-child(even),
.rvt-table-stripes tr:nth-child(even) {
  background-color: #f7f7f7;  <-- proposed change: #f0f0f0;
}

**Comment by zttodd** [comment]
We would like to troubleshoot this issue further. Would you be able to provide the following details?

- Resolution of display
- Operating system
- Browser (with version if you're using Internet Explorer)
