### ISSUE TITLE
(Possible) Accessibility issue with `.visuallyhidden, .v-hide, .sr-only`

### ISSUE THREAD

**Issue by nbannist** [indiana-university/rivet-source#179]
## Describe the bug
Screen readers might read the text in visually hidden blocks as all one word as outlined in the following article:
https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe

I just read it so haven't had a chance to verify either the bug or the fix (which looks super simple, which is nice). After reading the comments, it seems the issue shows up on Firefox on a PC, which I can't easily check. It seems to work fine in Narrator. But can't check NVDA or JAWS.

## Expected behavior
Probably should keep spaces between words.

## Relevant context (required)
Article that talks about the bug and the remedy: https://medium.com/@jessebeach/beware-smushed-off-screen-accessible-text-5952a4c2cbfe
OS: Windows
Browser: Firefox
Screenreader: ???

## Steps to reproduce
I can't reproduce without NVDA or JAWS.

**Comment by zttodd** [comment]
Closing this issue due to lack of verifiable Rivet example. Please feel free to reopen this in the future with more info or links to test cases.
