### ISSUE TITLE
Feature request: Timeline

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#18]
A component used to show historical interaction within a system, currently being used in IU Classifieds Administration to view an individual user's interaction of ad postings:

http://www.indiana.edu/~espd/rvb/develop/php/lib-extra-timeline.php

**Comment by illusivesunrae** [comment]
I went back and investigated the timeline that we incorporated into the OVPUE version of the framework during my time there, and found that we used the [CodyHouse Timeline](https://codyhouse.co/gem/vertical-timeline/) as the base. An example of the OVPUE framework timeline is available on the [Wells Scholars Program website](https://wellsscholars.indiana.edu/deadlines/office-admissions.html).

**Comment by illusivesunrae** [comment]
Released in PR #140.
