### ISSUE TITLE
Improve rendering of custom checkboxes in Firefox and Edge

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#180]
## Describe the bug
This one was reported to me from another developer. Looks like there are some rendering issues with custom checkboxes in Firefox and Edge when the the user has the browser zoomed out. 

## Expected behavior
This may just be a limitation of 1px borders on the checkbox. I'm not 100% sure this is a solvable issue, or one that needs to be a huge priority, but I think we can look into the possibility of increasing the border width to help with the rendering jank that's happening in these two browsers when zoomed out.

## Relevant context (required)
Screenshot submitted:
![image](https://user-images.githubusercontent.com/5590034/63887330-9270cc80-c9aa-11e9-9258-a48a83d5d2ce.png)

## Steps to reproduce
Add steps to reproduce the bug.

1. Visit any page with a visible Rivet checkbox in Edge or Firefox
1. Zoom out to at least 80%

## Notes from my conversation with developer who spotted the issue
> I don’t think we’ll ever get things to render the same in every browser (although Edge won’t be an issue soon since it will have Chrome guts), but I’ll go ahead and create an issue so that we can spend some time looking into it. Seems like the edges of the checkbox only disappear when you zoom _out_ which isn’t as concerning for me. We generally try to err on the side of making things more accessible, and generally speaking, folks who are having trouble seeing tend to zoom _in_. I think we could look at thickening up the borders a bit to help ease the rendering jank in FireFox though.

**Comment by scottanthonymurray** [comment]
We'll address this issue as part of Rivet 2 development.
