### ISSUE TITLE
Multiple buttons (switches, tabs, etc) in a form cause them to be activated when pressing enter key

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#182]
When in a form text input and pressing enter the first button[type="submit"] is activated. Therefore every button that is not meant to submit the form should be <button type="button"> because type "submit" is default for <button>. I have many buttons in my form for things like toggle switches and panel tabs. When I press enter I get them activated instead of submitting. I get around this by being explicit about adding type="button" to each of them that shouldn't submit the form.

**Comment by jolamar** [comment]
<img width="639" alt="Screen Shot 2019-09-05 at 1 19 01 PM" src="https://user-images.githubusercontent.com/1017119/64372969-bd2cd780-cfdf-11e9-8c2f-b2b33276ebfc.png">
here's a screenshot to illustrate the problem

**Comment by levimcg** [comment]
Just a quick heads up. I want to make sure I'm understanding your issue.

What you're describing is a default HTML behavior that Rivet itself doesn't really have control over. That said we do have a note in the documentation that calls this behavior out and that you are responsible for the implementation details in your app e.g. adding the `type="button"` attribute where appropriate.

https://rivet.iu.edu/components/forms/buttons/#button-types

We could look at expanding, or clarifying that language, but I'm not sure there's any technical solution (outside of documentation) we could offer. Definitely open to any suggestions you might have.

**Comment by jolamar** [comment]
You're totally right and I admit I didn't read the documentation. The only technical solution I can suggest is adding type="button" to any Rivet components (code examples) that use buttons in case they end up in forms. I don't think this is a technical issue now that you put it like that so I'll close this issue. Thanks!
