### ISSUE TITLE
Feature request: Clear field

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#19]
A simple component to easily clear a text input field after data has been entered. This is especially convenient on mobile/touch screen interactions:

http://www.indiana.edu/~espd/rvb/develop/php/lib-extra-clearfield.php

**Comment by maurercw** [comment]
I have this simple add-on that I worked on a while ago:
https://github.com/maurercw/rivet-clearable-input
Perhaps it could be easily incorporated into the main code!

**Comment by levimcg** [comment]
@maurercw this was on my list to review a while back and I totally dropped the ball. I apologize for that.

There were a couple of issues I noticed at first glance. I'll create issues for them on your repo, and then we can move forward from there. I'll do that ASAP.

**Comment by levimcg** [comment]
@maurercw I created some issues [on your repo](https://github.com/maurercw/rivet-clearable-input). Again, sorry for the delay 😬 

Let me know if you have any questions or need clarification 👍
