### ISSUE TITLE
Rivet Table not fully compatible with mobile layouts

### ISSUE THREAD

**Issue by nrtabor** [indiana-university/rivet-source#194]
## Describe the bug
When implementing pages in Rivet, tables do not sufficiently condense or reflow such that the layout fits on small mobile displays. Instead, the table will overflow the right side of the page and cause horizontal scrolling which exceeds the width of the header and footer.

## Expected behavior
The table should reflow in such a way that table width is less than the header and footer width, so that horizontal scrolling is not required. For a great example of how this can be done, see the IU Web Framework.

## Relevant context (required)
For example, on my OnePlus 6T, the screen resolution when browsing with Chrome returns 412 x 892. When viewing https://rivet.iu.edu/components/page-content/tables/, Every sample 3 column table on that page overflows the containing "rvtd-example__demo" div. 
When running the same test on a larger table, the columns continue further to the right and the problem becomes much more apparent.

![Screen Shot 2019-09-17 at 10 27 45](https://user-images.githubusercontent.com/55448999/65050694-cef27100-d935-11e9-99ae-be84d1975a6a.png)

## Steps to reproduce
View https://rivet.iu.edu/components/page-content/tables/, or any other rivet table with a sufficient number of columns, on a mobile device with a sufficiently small display width.

**Comment by levimcg** [comment]
Thank you for opening this issue. We currently have an issue open in our backlog for adding responsive tables. I'm going to mark this as a duplicate and close. Please see #16 for the original responsive tables feature request.
