### ISSUE TITLE
Sidebar navigation

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#202]
**Code reference:**
https://codepen.io/zttodd/pen/NWKZVdY

**To Dos:**
- [x] Markup
- [x] Styles
- [x] JavaScript
- [ ] Accessibility
- [ ] Documentation
- [x] Feature PR created for review
- [x] Merged into Rivet v2 alpha

**Comment by illusivesunrae** [comment]
Merged into `2.0.0-dev` with PR #219. 
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
