### ISSUE TITLE
Set up Fractal to publish to new development url

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#203]
I have created new a new Sitehost account and virtual host for the Rivet version 2 staging URL (will post here once it's live).

@illusivesunrae @zttodd I have added you both developer access to the new group account so either of you should be able to work on this.

As we begin work on v2, let's set up Fractal to start publishing to this new account based on any pushes/merges to the new v2 development branch once it is created.

**Comment by illusivesunrae** [comment]
Awesome! Sounds great! 🙌

**Comment by illusivesunrae** [comment]
After some thought, we have decided not to migrate the Fractal site to `rvtnext`, but instead to our `dsdev` account. There is some thought of creating an interim marketing site on `rvtnext` between now and creating documentation for v2.

We will create a new issue once we have a more concrete idea of what the interim site looks like.
