### ISSUE TITLE
Alerts within Alert lists do not close when a close element is added

### ISSUE THREAD

**Issue by ohnoitsaustin** [indiana-university/rivet-source#209]
## Describe the bug
When using 

## Expected behavior
When a `<button>` is placed within an Alert in an `alert-list` and given the `data-alert-close` attribute, the alert should close. Ideally, it would clean up any `<li>` or `<ul>` elements that are no longer needed as well.

## Relevant context (required)
Using [Alert lists](https://rivet.iu.edu/components/overlays/alerts/#alert-lists) should allow the usage of a close button within them. Instead, if a close button is added and clicked, the following console error appears:
```
rivet.min.js:8 Uncaught Error: Please proved an id attribute for the alert you want to dismiss.
    at o (rivet.min.js:8)
    at HTMLDocument.r (rivet.min.js:8)
```
## Steps to reproduce
Bug is reproduced in this codepen, which uses the example Alert list markup provided on the Rivet site, with the addition of a close button on the first alert https://codepen.io/ohnoitsaustin/pen/MWWrjMX

**Comment by nbannist** [comment]
As a temp work around, people could use the old method outlined in the following codepen: 
https://codepen.io/nbannist/pen/KKKZNKo

Basically, each list item has an element with a class of `rvt-alert`. So, on that element, add an `aria-labelledby` attribute whose value matches the `id` attribute on the `h1` inside that `rvt-alert` element.

Then a regular dismiss button should work to close the item the button is in.

```
<button type="button" class="rvt-alert__dismiss">
  <span class="v-hide">Dismiss this alert</span>
  <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
    <path fill="currentColor" d="M9.41,8l5.29-5.29a1,1,0,0,0-1.41-1.41L8,6.59,2.71,1.29A1,1,0,0,0,1.29,2.71L6.59,8,1.29,13.29a1,1,0,1,0,1.41,1.41L8,9.41l5.29,5.29a1,1,0,0,0,1.41-1.41Z"/>
  </svg>
</button>
```

**Comment by nbannist** [comment]
The error message has a small typo too: "proved" -> "provide"

**Comment by levimcg** [comment]
@ohnoitsaustin In the codepen you provided you are missing the required `data-alert-close` attribute on the "X" button. the alert itself should also have an `aria-labelledby` or `id` (either will work) attribute which is both used to grab the alert and remove it from the DOM (admittedly this implementation could be better) and tie the alert title to the alert itself for accessibility reasons (aria-labelledby). When I added those attributes to your demo the alert is dismissed/removed from the DOM as expected. Just an FYI, if you're needing this to work now.

The new-ish `data-alert-close` implementation was made to be backwards compatible with older versions of rivet so as to avoid a breaking changes, but here is some background on the change:

- https://rivet.iu.edu/components/overlays/alerts/#javascript-api
- PR covering this change: https://github.com/indiana-university/rivet-source/issues/85

It does make sense that if an alert is in a list that dismissing it should clean up the list item as well. I'd have to think through how that would work on a practical level.
