### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#212]
Now that we are going to begin development on the Rivet 2, we need to evaluate the current code base to look for any deprecated code that can be removed.

Most of the deprecated code will be isolated to the Sass files. I've done my best to mark anything that should be removed in the next breaking changes with a `DEPRECATED:` comment, so searching the code base to find things that need removed should be pretty straightforward.

Things to look for are old un-prefixed css classes. the first couple minor version of Rivet did not namespace the CSS classes with `rvt` so there are a lot of places where you'll see duplicated CSS classes in declarations. For example:

```scss
.text-bold,
.#{$prefix}-text-bold {
  font-weight: 700;
}
```

In these cases we need to remove the older un-prefixed versions where they exist.

@illusivesunrae @zttodd I'm happy to get together to chat about this in person if there are any questions.

**Comment by zttodd** [comment]
After working through removing deprecated and non-prefixed selectors within `src/sass`, these files will need further review to evaluate how to to handle more general non-prefixed selectors.

`components`
- [ ] _checkboxes.scss
- [ ] _inputs.scss
- [ ] _radios.scss
- [ ] _tables.scss

`core`
- [ ] _base.scss
- [ ] _tools.scss

**Comment by illusivesunrae** [comment]
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha).
