### ISSUE TITLE
Re-evaluate build process and include JavaScript bundling step(s)

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#213]
## Summary
We've been using Gulp for all build process for a while now. Since we will need to rework some of the build process to add support for writing modern JavaScript modules and bundling them, it probably makes sense to re-evaluate our build process as we get started on Rivet 2. I'm perfectly happy to continue down the Gulp path for the main build tool, but I'm definitely open to new ideas if it makes our lives easier.

## Describe the solution you'd like
I'd prefer that we use Rollup.js for JavaScript bundling since we are building libraries to get distributed, and due to its relative ease of use compared to other tools. In the end we'll need to be able to have a main entry point that imports a bunch of JS modules and builds a IIFE/browser bundle, as well as a ES module bundle to ship in the NPM package.

## Similar features or implementations
We are already using Rollup and Gulp [here in the add-on boilerplate repo](https://github.com/indiana-university/rivet-add-on-boilerplate/blob/develop/gulpfile.js#L121), so the same sort of set up should be relatively straightforward to add to the rivet-source repo.

**Comment by illusivesunrae** [comment]
I completely agree. Having done a deep dive into webpack, gulp, and grunt recently, I think (of those three) gulp is the best fix for us; however, there is a lot we can do to smooth out our processes. As far as Rollup.js goes, I think it's a great tool. It has really good integrations with Babel, Uglify.js, etc., and I think we have a pretty good handle on how it works. 💯

Anyway, I'll put together a sample repo to play around with how to best optimize our builds.

**Comment by illusivesunrae** [comment]
Merged into `2.0.0-dev` with PR #217. 
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
