### ISSUE TITLE
Create documented color utility CSS classes that correspond to all Sass color variable

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#226]
## Summary
We already store all of Rivet's colors in Sass variable (`_variables.scss`). We should include color and background-color CSS utilities in Rivet.

## Describe the solution you'd like
I'd like to be able to change the `color` and/or `background-color` css properties of an element with a concise CSS utility class.

For example this would change the `color` of the following `div`:

```html
<div class="rvt-color-black-500">
  This text will be a the same value as the $color-black-500 Sass variable
</div>
```

```html
<div class="rvt-bg-blue-100">
  This text would have a subtle blue background the same value as the $color-blue-100 Sass variable
</div>
```

## Describe alternatives you've considered
Not really considered anything else other than not offering any color utilities. We do need to take special care to document how to use these utilities really well including how to create accessible color combinations.

## Additional context
As I mentioned above, we'll need to take special care to document how these color utilities should be used, and especially how they _**should not**_ be used e.g. inaccessible color combinations, clashing color combinations, and color combinations that don't express the IU brand.

### Rethinking Sass variable structure
This will also require some rethinking of the way we store and use Rivet's color Sass variables. Right now they are all regular variables, but it would be useful to move all the key/value pairs into a Sass map that we can use to iterate/loop through and easily output all of these utilities.

**Comment by illusivesunrae** [comment]
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
