### ISSUE TITLE
Vanilla JS components: Refactor Dropdown

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#229]
## ✏️ Summary
As begin implementing the new _Vanilla JavaScript Components_ strategy laid out [in this RFC](https://github.com/indiana-university/rivet-rfcs/blob/rfc/vanilla-js-components/text/0001-vanilla-js-components.md), we'll need to refactor/rewrite the [current Dropdown component](https://github.com/indiana-university/rivet-source/blob/master/src/js/components/dropdown.js).

Refer to [the RFC text](https://github.com/indiana-university/rivet-rfcs/blob/rfc/vanilla-js-components/text/0001-vanilla-js-components.md) for guidance and general direction.

## ✅ Development Checklist
- [x] Component should be an ES6 `class`
- [x] Component should be able to be programmatically controlled via "public" methods
- [ ] Component should emit `customEvent`s as hooks when appropriate
- [x] Public component methods should have callback functions where appropriate (let's talk more about this as we get started)
- [x] Components should use data attributes as hooks for functionality and follow the format `data-[component-name]`
- [ ] `customEvent`s should be cancelable by the developer using them
- [x] Should be tested and function all evergreen modern browsers and IE11
- [x] All methods should be documented using [JSDoc-style comments](https://jsdoc.app/index.html)
- [x] Component should have end-to-end (Cypress) tests that cover the functionality of all public methods, interactions e.g. open/close, show/hide, and any `customEvent`s the component emits.

## 👇 Example component structure
Here's an example of the new Sidenav component that follows the structure and mostly meets the criteria above. This shouldn't be considered the definitive pattern/style for all components, but might be helpful to use as an example when getting started.

✨ [**New Sidenav component**](https://github.com/indiana-university/rivet-source/blob/2.0.0-dev/src/js/components/sidenav.js) ✨

**Comment by levimcg** [comment]
As a part of this refactor let's make sure to address #136

**Comment by illusivesunrae** [comment]
Merged into `2.0.0-dev` with PR #248.

**Comment by illusivesunrae** [comment]
Released with PR #294.
