### ISSUE TITLE
Additional flexbox utilities

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#23]
It came up recently that we wanted some content centered within a grid item that's also a flex. There does not appear to be a util within Rivet currently to do this.

The workaround was to make a custom css class that does:

`justify-content: center;`

Would be preferable if there was an option within Rivet to center content inside of various containers/grids/flexes/panels in general.

**Comment by levimcg** [comment]
**Moved this issue comment over to github.com**:

---

This would make a nice addition.

I've been thinking a lot about how there is probably a good case for a more robust set of flex utility classes. I find myself needing things like what you described above pretty often. I'd like to see a new set of flexbox specific utils like:

.rvt-flex (for setting display flex)
.rvt-justify-center (for justify-content: center)
.rvt-flex-start (for justify-content: flex-start)
.rvt-flex-end (for justify-content: flex-end)
etc...
I think a set of utilities would like this would be super helpful for fine-tuning flex layouts where using the grid (or nesting a grid) is maybe too much.

Would you find something like that useful?

**Comment by levimcg** [comment]
Updating this issue name to more accurately reflect the request.

This is something that I'd like move up in terms of priority. As we move toward providing more full-formed page templates, etc. These kind of utilities will be super useful.

**Comment by scottanthonymurray** [comment]
Added in `1.3.0`:

https://rivet.iu.edu/components/utilities/flex/
