### ISSUE TITLE
Update color scale naming conventions

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#234]
In PR #233 we discussed updating the color scale variable naming conventions. Based on that discussion let's move forward with this update. This will involve using a single dash in place of double dashes in each variable name, so `--100` becomes `-100`, and converting the variable name for the lightest tint of each color from `--050` to `-000`.

Here's an example of what the blue color scale variables would look like after this update.

```scss
$color-blue-000: #edf1f6 !default;
$color-blue-100: #dce3ee !default;
$color-blue-200: #b8c8dc !default;
$color-blue-300: #95adcb !default;
$color-blue-400: #7194ba !default;
$color-blue-500: #497ba9 !default;
$color-blue-600: $color-blue !default;
$color-blue-700: #134a71 !default;
$color-blue-800: #16324b !default;
$color-blue-900: #121c28 !default;
```

This update should be applied to all colors that follow this color scale naming convention.

- [x] Black
- [x] Blue
- [x] Green
- [x] Yellow
- [x] Orange

**Comment by illusivesunrae** [comment]
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
