### ISSUE TITLE
add "none" alias to "-p-remove" and "-m-remove" classes

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#24]
Several developers (myself included) have expected for there to be a `-none` version of the `rvt-m-[side]-[size]` classes, e.g. `rvt-m-bottom-none`. While `rvt-m-bottom-remove` does it exist, it has proved to be unintuitive based on the naming of the other classes.

I propose adding a `*-none` alias to any class that includes `*-remove`, in order to better meet developer expectations.

Additionally, documentation on the spacing page (https://rivet.iu.edu/components/layout/spacing/#no-spacing) should be updated to include the alias, as well as to spell out the different `-none` classes that are available. It currently only documents `rvt-m-all-remove` and `rvt-p-all-remove`, without mentioning that similar classes exist for top, right, bottom, and left as well.

**Comment by levimcg** [comment]
Closed via #55
