### ISSUE TITLE
Automate attaching .zip file of CSS and JS assets to GitHub release

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#247]
## Summary
When a Rivet release is created we attach the a .zip file containing the Sass source and compiled JavaScript and CSS file to the release. We then link to this zip file as the _Download_ on the documentation site.

I'd like to automate that process is some way if possible. The .zip file gets built durring the release process via GitHub action, it seems like there should be some way to attach that zip file (artifact) to the GitHub Release with some combination of the GitHub API and Actions.

## Similar features or implementations
There are a lot of great resources for GitHub actions on this list:

https://github.com/sdras/awesome-actions

This one called _upload-release-asset_ might be the one we're looking for, but I'm not 100% sure:

https://github.com/actions/upload-release-asset

## Additional context
We may also need to automate the creation of the GitHub Release since the release process is first kicked off by pushing a tag.

**Comment by illusivesunrae** [comment]
Released with PR #294.
