### ISSUE TITLE
Vanilla JS Components: Create new Accordion component

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#249]
## Summary
Rivet doesn't have an official Accordion component as it were. The [Collapsible add-on](https://rivet.iu.edu/add-ons/rivet-collapsible/) has to option to be configured as a component, but for Rivet 2 I'd like to see the Accordion become its own component and then move the Collapsible add-on into Rivet core as a separate component (separate issue) that provides as a progressive disclosure/show/hide functionality only (similar to the native HTML `details` element).

## Describe the solution you'd like
The existing code for the Collapsible accordion functionality should be a good start in terms of building the toggle functionality and support for keyboard navigation, but will need to be adapted to match the JavaScript design patterns we're currently using for the other Vanilla JS Components.

As far as CSS/styling goes, we can use the existing Collapsible styles for now and revisit the design a little further down the line as the 2.0 visual style starts to firm up a little more.

## Similar features or implementations
- [Existing Collapsible accordion configuration](https://rivet.iu.edu/add-ons/rivet-collapsible/)
- [Web Style Guid Accordion Chunk](https://styleguide.iu.edu/pattern-library/chunks/accordion.html)

## Additional context
Here's a link to the ARIA Authoring requirements for states, roles, keyboard functionality, etc. https://w3c.github.io/aria-practices/#accordion

### Note on keyboard functionality
Although the ARIA spec marks some keyboard functionality as option I'd like to fully implement the recommendation. That means the following:

- Focus should cycle from the last panel header to the first and vice versa when the down/up arrow key is pressed.
- Focus should move to the last panel header when the `End` key is pressed
- Focus should move to the first panel header when the `Home` key is pressed
- See the [_Keyboard Interaction_ section](https://w3c.github.io/aria-practices/#keyb) in the ARIA docs for details

**Comment by illusivesunrae** [comment]
Released with PR #294.
