### ISSUE TITLE
Only transpile browser JavaScript builds (iife) and leave ES module build as named exports

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#254]
I was doing some testing with the first 2.0.0-alpha and noticed a couple of things that could be improved:

1. For the ES module build we **should not** compile the bundle using Babel. I think it makes more sense to go ahead and ship an ES module bundle that uses modern JavaScript with named exports and leave the compiling/transpiling to the developers that choose to use it and their own build tools/browser support targets.
2. In `index.js` we are exporting a `default` object with all of the components E.g. `{ Alert, Sidenav, ... }`. This makes it so when you use a bundler you need it import all of the components and then access the component you want using dot notation. E.g. `import Rivet from 'rivet-core'` then to use the Sidenav component you have to call `new Rivet.Sidenav()`. It would be nice to use named exports instead so that you could pull out only what you need. E.g. `import { Sidenav } from 'rivet-core` and then use it like, `new Sidenav()`. This would also allow build tools that support it to do _treeshaking_ and removed unused code making bundles sizes smaller for those who only need certain components after we fix point 1. from above. 
3. We need to add a `"main"` and `"module"` field to the `package.json` so that build tools and IDEs that support it will be able to use the [Node.js resolution algorithm ](https://nodejs.org/api/modules.html#modules_all_together) to find the ES module bundle inside of `node_modules`. Both values should be set to the `js/rivet-esm.js` bundle that gets build in the npm package.

I think this is mostly tweaking the rollup build process and only using the Babel plugin on the browser bundle that gets shipped.

**Comment by illusivesunrae** [comment]
Released with PR #294.
