### ISSUE TITLE
Implement RFC 0003 - More modular Sass

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#264]
Creating this issue to prioritize work no the _More modular Sass_ RFC. I'll be leaving the RFC open for a while as we work out the details on a more standard timeline for RFCs and to see if we get anymore feedback in the coming weeks, but we can go ahead and get started on this.

See the [_Detailed design_](https://github.com/indiana-university/rivet-rfcs/blob/rfc/modular-sass/text/0003-modular-sass.md#detailed-design) section of the full RFC text for implementation details.

**Comment by illusivesunrae** [comment]
Released with PR #294.
