### ISSUE TITLE
Implement RFC 0002 - Container and grid simplification

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#265]
Creating this issue to prioritize work no the _Container and grid simplification_ RFC. I'll be leaving the RFC open for a while as we work out the details on a more standard timeline for RFCs and to see if we get anymore feedback in the coming weeks, but we can go ahead and get started on this.

See [Detailed design section](https://github.com/indiana-university/rivet-rfcs/blob/rfc/container-and-grid-simplification/text/0002-container-and-grid-simplification.md#detailed-design) of the RFC text for implementation details.

**Comment by illusivesunrae** [comment]
Released with PR #294.
