### ISSUE TITLE
Setup codepen for rivet docs

### ISSUE THREAD

**Issue by illusivesunrae** [indiana-university/rivet-source#276]
## Summary
Many documentation websites have moved toward providing code examples in codepen for developers to copy, reference, sandbox. This would be a great addition to the Rivet 2.x documentation website.

## Describe the solution you'd like
Create a codepen account for the rivet@iu.edu address, and create codepen examples for Rivet 2.x components, etc.

## Similar features or implementations
[Duet](https://www.duetds.com/components/checkbox/) has good examples of this.

**Comment by scottanthonymurray** [comment]
Closing this issue and adding this task to our internal project management app.
