### ISSUE TITLE
Revise color scale for black

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#28]
We've recently updated implemented a consistent color scale for all of the major colors in Rivet (see #403 ). The last remaining color that needs updated is black. 

I've generated a new black color scale here that incorporates a subtle reference to the blue color that we use throughout Rivet to indicate interactivity/action:

https://codepen.io/levimcg/pen/NeGGoy

This Codepen shows a new proposed black color scale next to the newly implemented consistent color scales for the rest of the Rivet colors. This is a pretty subtle change in black overall, but one that will help improve the visual consistency of Rivet overall.

## Challenges
While implementing this new black color scale wouldn't be a breaking change per se, but it would cause a somewhat significant shift in the lightness/darkness for the 10 black color variants (Sass variables) that ship with Rivet currently.

So, while it wouldn't break anything in a code base that is taking advantage of using any of these Sass variables, the color changes would be noticeable depending on the colors being used, especially in the lighter tints of black (`$color-black--100`, `$color-black--200`, etc.).

**Comment by illusivesunrae** [comment]
Merged into develop with PR #233.
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
