### ISSUE TITLE
Move base reset styles into opt-in classes

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#281]
## Summary
To prevent collisions of base styles (html, h1, h2, h3, etc) with other libraries, the reset styles can be moved into CSS classes that are opt-in only.

## Describe the solution you'd like
Explore moving these styles into opt-in CSS classes, into specific components, and/or within a namespacing solution that doesn't cause specificity issues.

**Comment by illusivesunrae** [comment]
Released with PR #355.
