### ISSUE TITLE
Consider moving Spacing & Typography to Utilities

### ISSUE THREAD

**Issue by avr** [indiana-university/rivet-source#282]
The Spacing and Typography components make more sense as Utilities vs. Layout.  Layout generally refers to larger, page-wide adjustments.  Utilities seem to be more specific to individual elements.

In general, I'm find myself adding spacing and typography to headers or wrapper divs around 1 or 2 items (vs. larger containers).

**Comment by illusivesunrae** [comment]
Merged into `2.0.0-dev` with PR #216.
Published to `2.0.0-alpha` with Release [v2.0.0-alpha](https://github.com/indiana-university/rivet-source/releases/tag/v2.0.0-alpha)
