### ISSUE TITLE
Remove Fractal-specific element state classes

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#290]
In `src/sass/buttons/_base.scss`, there are element state classes present for testing components within Fractal. These include classes for focus, hover, and active states. These only need to be included for use with Fractal and don't need to be included within production Rivet Sass/CSS. In each of these cases, the pseudo-element and the styles will remain, but the class will be removed.

**Button example:**
```
  &:hover,
  &--hover {
    background-color: $color-blue-700;
    border-color: $color-blue-700;
    color: $color-white;
  }
```

becomes:

```
  &:hover {
    background-color: $color-blue-700;
    border-color: $color-blue-700;
    color: $color-white;
  }
```

**Secondary button example:**
```
  &:hover,
  &--hover {
    background-color: $color-blue-700;
    border-color: $color-blue-700;
    color: $color-white;
  }
```

becomes:

```
  &:hover {
    background-color: $color-blue-700;
    border-color: $color-blue-700;
    color: $color-white;
  }
```

**Comment by illusivesunrae** [comment]
Released with PR #355.
