### ISSUE TITLE
Consolidate Style Dictionary includes in gulpfile.js

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#293]
The Style Dictionary includes in the `gulpfile.js` could be combined into one file with different exports. For example, these `filter` includes:

```
const isBreakpoint = require('./src/tokens/filters/is-breakpoint');
const isColor = require('./src/tokens/filters/is-color');
const isTypeScale = require('./src/tokens/filters/is-type-scale');
const isWidth = require('./src/tokens/filters/is-width');
const isZIndex = require('./src/tokens/filters/is-z-index');
```

Could be combined into one file (and refactored to a loop since the file contents are all very similar) and then set up as named exports to be imported within `gulpfile.js`.

Reference comment here: https://github.com/indiana-university/rivet-source/pull/283

**Comment by illusivesunrae** [comment]
Released with PR #355.
