### ISSUE TITLE
Create Quote Component

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#295]
Review existing style guide documentation:
https://styleguide.iu.edu/pattern-library/chunks/callout-pullquote.html

This issue will be for the blockquote component only. For the version with a profile image will be dependent on the new avatar component currently being tracked in #288.

Here's a quick codepen prototype I put together while working on some layout experiments to use as a start. It will need to have variable names, etc. updated to match new sass variable names.

https://codepen.io/levimcg/pen/BaNoOGZ

**Comment by illusivesunrae** [comment]
Released with PR #355.
