### ISSUE TITLE
Update index.js to export components as named exports

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#299]
This was previously fixed, but was overridden by some other commit. Instead of exporting the components within on `default`, they should be each exported as named exports.

**src/index.js:**

`export default { Accordion, Alert, Dropdown, FileInput, Modal, Sidenav, Tabs };`

should become:

`export { Accordion, Alert, Dropdown, FileInput, Modal, Sidenav, Tabs };`

Original issue: https://github.com/indiana-university/rivet-source/issues/254
Previously merged PR: https://github.com/indiana-university/rivet-source/pull/256/commits/c71a007b47d87be079641d77799f135f4bf7d677

**Comment by illusivesunrae** [comment]
Released with PR #355.
