### ISSUE TITLE
Tab styling - simple style suggestion

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#3]
For the upcoming AdRx redesign, we created tabs with a more simple styling to simplify the navigation of the pages. 

We thoroughly usability tested this tab design, and the tabs shown in the attached screen shot tested very well (see Advising Snapshot, Contact History, Academic Info, etc tab navigation towards the top of the content).

Additionally, the tabs within the card (under Alerts) also tested well.

This would offer a more universal tab option to accommodate a wider range of designs and placement when the more traditional tabs in Rivet may not integrate into the design well.

![image](https://media.github.iu.edu/user/3666/files/c06b0020-9ee4-11e8-8521-95dce9fb04ea)

![image](https://media.github.iu.edu/user/3666/files/f5ce4b6e-9ee4-11e8-89b6-26d22417ec16)

**Comment by levimcg** [comment]
I've started working on this plain version of the Rivet tabs in this codepen:

https://codepen.io/levimcg/pen/jQrZNV

@christiemh54 Would love some feedback on this direction if you have the chance. Thanks 🙌

**Comment by basham** [comment]
Some feedback:

1. I would like to see this styling extend beyond tabs. This could be used as a form of horizontal navigation, if the items are links instead of buttons. In the particular case of AdRx, this feels more appropriate as links, so you could deep link into an area. Example: `adrx.iu.edu/students/0001234567/history`
2. When the panel is in focus, the focus outline bleeds right against the content. It would be good to establish some spacing somewhere.

**Comment by levimcg** [comment]
@basham 

1. Yes, I agree. I think we do need some form of supplemental horizontal navigation that can live outside of the main header. @madgrds been working on some concepts for reorganizing the Rivet docs and playing around with the idea of a horizontal _subnav_ (shown here in screenshot). Seems like there is a lot of overlap here. Something to think about 🤔 . 
![image](https://user-images.githubusercontent.com/5590034/52234127-e9884600-288e-11e9-9b52-07d861d4182e.png)
2. Good call we can definitely add some more spacing to the focus state.

**Comment by madgrds** [comment]
I've been using the Rivet site updates to experiment with different secondary headers + local nav options. Here are those sketches: 

[Secondary header](https://www.figma.com/file/RHZG6x9rzR8B2z3MMgJq8V7m/2019-Rivet-site-Homepage-Roadmap?node-id=40%3A0)

[Secondary header with sidebar exploration](https://www.figma.com/file/RHZG6x9rzR8B2z3MMgJq8V7m/2019-Rivet-site-Homepage-Roadmap?node-id=191%3A77)

Don't hesitate to share your thoughts!

**Comment by levimcg** [comment]
Just a quick follow-up on this. I've put together a quick sketch/demo of some ideas for this new subnav/secondary-nav component.

https://codepen.io/levimcg/pen/aXydOJ

While, a plain variant of the tabs component is a good idea, I think this would need to be a new component separate from the actual [Tabs component](https://rivet.iu.edu/components/page-content/tabs/) that can be used in a more flexible way as @basham mentioned.

In the demo I've sketched out what I feel like are some typical uses and layouts for this kind of horizontal navigation component. For example:

- positioned directly under the main rivet header
- constrained to a fixed-width using a [Rivet container](https://rivet.iu.edu/components/layout/grid/#the-container) element
- used inside of a Rivet grid item

I'd appreciate any feedback or suggestions.

**Comment by madgrds** [comment]
@levimcg, that hover state is 👍!

I'm digging this. You can definitely see how they "layer" on one another, which is great. 

Something to consider, if you haven't already: I remember we once discussed how internal tabs could get tricky. Someone may to use tabs for an internal chunk, similar to the designs for [tints on the Rivet colors page](https://www.figma.com/proto/ftjyICgLRouK2MKyamaO3dZo/Rivet-colors?node-id=0%3A1&scaling=min-zoom). Without borders, it may look like content below the chunk was part of the chunk. (Does that make sense?) 

Is that something we'll want to address in the documentation, or should we have a fourth version with borders?

**Comment by levimcg** [comment]
@madgrds Cool, thanks for the feedback! Yes, I think we'll definitely need to make the distinction clear between what this new horizontal nav/subnav component and any version of the tabs.

**Comment by basham** [comment]
Feedback:
1. We should not introduce a new focus style (dashed outline). Stick with the standard solid line.
2. The hover styles for an active verses inactive tab seems startling. Perhaps have one consistent way to do hover. For example, use the same light blue background or (my preference for consistency sake) just do a simple text underline, like what's in the header nav.

**Comment by levimcg** [comment]
Just a heads up, we are planning to use this horizontal navigation as one of the patterns we'll be having teams design/build in the upcoming community workshop. We'll save it for an upcoming release.

**Comment by illusivesunrae** [comment]
Pulled into master with PR #117.
