### ISSUE TITLE
Process steps completed indicator. 

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#35]
Something that is a like the progress bar in ApplyIU, that can be used/configured similar to the breadcrumb React component. Ideally it could be styled for vertical or horizontal use.

**Comment by krishancock** [comment]
I'm working on something like this for ESS. Here's a link to the design:

https://tt6lt5.axshare.com

**Comment by wbobe** [comment]
The last two years we did two different methods of handling this for Statewide. In 2017 Patrick built something very similar to the ApplyIU one. Last year I think I just used Rivet breadcrumbs. I could show you examples of both of the solutions, if you want.

**Comment by jameswilson** [comment]
This would be an interesting feature to standardize.  The Libraries website — currently using framework, not rivets — implemented the following solution:

https://libraries.indiana.edu/request-educational-access-library-subscription-electronic-resources-another-campus
https://libraries.indiana.edu/rush-cataloging-request

**Comment by levimcg** [comment]
@wbobe @jameswilson Awesome, thanks for sharing. This was actually one of the projects we used in our first community workshop we had just a couple of weeks ago. We have a branch open right now that is based off of the work that the team in the workshop did:

https://github.com/indiana-university/rivet-source/tree/feature/step-indicator

We had hoped to get it into our latest release (yesterday), but weren't able to get testing and documentation done in time. But, it's looking like we're in pretty good shape to get it into the release next month!

**Comment by illusivesunrae** [comment]
Pulled into master with PR #117.
