### ISSUE TITLE
Dropdown icon diffs

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#36]
This is just a super nitpicky pixel thing...but it seems that the embedded svg dropdown icon is visually different from the dropdown icon found in the Rivet Icon library. In the screenshot, top example is the embedded svg, bottom example is from the icon library. Not a big deal...just something I noticed, thought I'd share:
<img width="202" alt="screen shot 2018-06-22 at 10 35 32 am" src="https://github.iu.edu/storage/user/2515/files/09527f60-760a-11e8-86ef-8d0cc819cd8d">

**Comment by NikithaNadig** [comment]
Is someone assigned to this or can I work on this?

**Comment by scottanthonymurray** [comment]
@NikithaNadig Thanks for your interest in contributing to the Rivet design system!

Looking more closely, this is an issue with the documentation using the wrong SVG. I'll update the docs to use the correct icon.
