### ISSUE TITLE
Contextual focus styling

### ISSUE THREAD

**Issue by thrclark** [indiana-university/rivet-source#388]
This may be more of a personal style preference thing, but is there any reason why the focus outline styling on buttons is always the primary color, and not the actual context state color? For example, buttons styled with the 'danger' classes create a red button, but with blue focus styling:
![buttonfocus](https://user-images.githubusercontent.com/5652113/79355579-dbf73300-7f0b-11ea-856e-f31ec7f7bb0e.png)

**Comment by scottanthonymurray** [comment]
@thrclark Thanks for filing this issue! Sorry for the delay -- the members of the Rivet team were assigned to projects related to IU's coronavirus response last year and we're finally getting back to the design system.

Your suggestion is a great one, we'll make this change in the next release. 🚀
