### ISSUE TITLE
Using Columns in Navigation causes strange styles

### ISSUE THREAD

**Issue by UIDvlpr** [indiana-university/rivet-source#394]
## Describe the bug
IU Rivet utilizes the outline on many of its elements however the outline (in its current form) doesn't play nicely with the columns CSS property. The hover color and outline both bleed from column 1 into column 2.

## Expected behavior
What should happen is that each columns content (outlines and hover background color) is contained within that column without having to declare different columns in the HTML.

## Relevant context (required)
The issue - https://codepen.io/jpwade95/pen/zYrqNXv or https://medicine.iu.edu (view steps to reproduce to see the issue in action)
An idea on the fix - https://codepen.io/jpwade95/pen/gOPrmbK
![Screenshot (3)](https://user-images.githubusercontent.com/37874411/84428685-e58fd500-abf4-11ea-9963-66cf243bccbd.png)

## Steps to reproduce
1. Go to https://medicine.iu.edu/
2. Click on the dropdown arrow next to "Departments"
3. Hover over "Orthopaedic Surgery" (top right)

**Comment by levimcg** [comment]
@UIDvlpr Thanks for opening this and thanks for the codepen fix. The IUSM header with css columns was a custom implementation, but this is helpful to know for future versions. Thanks!

**Comment by scottanthonymurray** [comment]
Closing this issue as we do not plan on supporting the CSS `columns` property in the Rivet 1 header. We'll definitely consider it for Rivet 2, however.
