### ISSUE TITLE
Element must have sufficient color contrast

### ISSUE THREAD

**Issue by amalvank** [indiana-university/rivet-source#395]
The following issue is getting reported in our application. This issue also seems to be present on rivet.iu.edu.

Steps to recreate the issue :

1. Navigate to https://rivet.iu.edu/components/forms/select-input/
2. Run Axe Accessibility tool 

![image](https://user-images.githubusercontent.com/42578448/84706734-7c2d0080-af2b-11ea-9d51-a0b97516c102.png)

**Comment by scottanthonymurray** [comment]
This is a known false positive involving pseudo-selectors like `:nth-child` and background SVGs, which are triggering the "needs review" color contrast warnings on the Rivet page.
