### ISSUE TITLE
rvt-table-cell border missing on top of td column with no header in Chrome

### ISSUE THREAD

**Issue by gjthomas** [indiana-university/rivet-source#397]
## Describe the bug
When using the rvt-table-cell style and not using a <thead> in Rivet 1.7.2, the table renders fine in Firefox 80.0, but is missing the top border in Chrome 85.0.4183.83.

![rivetTableCell-Chrome](https://user-images.githubusercontent.com/8582408/93368624-39294480-f81c-11ea-94ae-f4d2471cd7b9.png)

## Expected behavior
Table borders and cells should render consistently in all browsers.

## Relevant context (required)
- Please refer to this codepen for possible fixes with the original table code that was used.
- https://codepen.io/basham/pen/poyZBmG?editors=1100

**Comment by basham** [comment]
Rivet should explore this variation some more. By far, the most common [table styles](https://rivet.iu.edu/components/page-content/tables/) are the ones that are already in the docs. But Rivet assumes that there will always be a `<thead>` of `<th>` elements. And if a `<th>` is in `<tbody>`, it should look like any other `<td>`. Greg's example is a simple key-value variation, with no need to explicitly label the columns. There needs to be some way to add the background color and bold font to the `<th>` elements in the `<tbody>`. But there should also be consideration of if you would want to have both a column of (styled) `<th>` elements and a row of `<th>` elements together. How would that look?
