### ISSUE TITLE
Incorporate font-weight 500

### ISSUE THREAD

**Issue by illusivesunrae** [indiana-university/rivet-source#400]
## Summary
Currently, IU's license for Benton Sans includes the font-weights 400, 500, and 700; however, currently only 400 and 700 have been incorporated into Rivet.

## Describe the solution you'd like
- Create a font-face declaration for Benton Sans Medium
- Add `$font-weight-medium` to already existing font-weight tokens
- Create `rvt-text-medium` companion css class to match already existing `rvt-text-bold` and `rvt-text-regular` classes

**Comment by scottanthonymurray** [comment]
I'm closing this issue, as we've been unable to get information on when the needed TTF/WOFF assets for this font weight will be hosted on the fonts.iu.edu domain.
