### ISSUE TITLE
Add font-display: swap to @font-face

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#406]
## Describe the bug
When pages using `rivet-2.0.0-alpha.3` are tested with Lighthouse in Google Chrome, this performance issue is flagged:

> Ensure text remains visible during webfont load 
> Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.

## Expected behavior

If `font-display: swap` is added to the flagged `@font-face` instances within the Rivet Sass, this will resolve this Lighthouse issue (and improve performance for swapping in custom fonts once they have been loaded).

## Relevant context (required)

![Screen Shot 2021-02-01 at 2 17 21 PM](https://user-images.githubusercontent.com/1396192/106507019-7bd07e00-6498-11eb-98c6-439a5a15f1bf.png).

## Steps to reproduce

Run Lighthouse from the Google Chrome DevTools on any page using `rivet-2.0.0-alpha.3` CSS assets, such as this page: https://www.iu.edu/index.html.

**Comment by scottanthonymurray** [comment]
Moving to our internal project management app for Rivet 2 development.
