### ISSUE TITLE
Migrate rvt-stretch-end class to Rivet 2.0

### ISSUE THREAD

**Issue by zttodd** [indiana-university/rivet-source#417]
## Describe the bug
The flex align-self class `rvt-stretch-end` is missing from the Rivet version `2.0.0-alpha.3`. This is a class that's available in Rivet 1, so it might be a good idea to consider migrating this into future alpha releases of 2.0. Or document if the class has changed to another name to be used instead.

## Expected behavior
In Rivet 1, adding the class `rvt-stretch-end` to a child element within a flexbox container will extend the element to the end of the container, either vertically or horizontally, depending on the `flex-direction`.

## Relevant context (required)
The class `rvt-stretch-end` is missing from the CSS hosted here: https://unpkg.com/browse/rivet-core@2.0.0-alpha.3/css/rivet.css.

## Steps to reproduce
When this class is used with `2.0.0-alpha.3`, no styles are found within the browser Dev Tools "Styles" tab and the element doesn't visually expand to the end of the container.

**Comment by scottanthonymurray** [comment]
Moving this issue to our internal project management app for Rivet 2 development.
