### ISSUE TITLE
Modal.close(id) sometimes throws an undefined exception

### ISSUE THREAD

**Issue by rileymg** [indiana-university/rivet-source#451]
Modal.close(id) sometimes throws the following js error:

rxjs.umd.min.js:50 Uncaught TypeError: Cannot read property 'dispatchEvent' of undefined
    at a (rivet.js:67)
    at Object.p [as close] (rivet.js:1186)
    at ve (util.js:585)
    at a.project (Content.intent.js:85)
    at a._next (rxjs.umd.min.js:128)
...

the offending line is in the fireCustomEvent() method:
     element.dispatchEvent(event)

...when called (in this instance) from Modal.close.

I overcame the issue by simply changing the offending line to:

     element && element.dispatchEvent(event)

Cause of issue:  I’m wondering if perhaps the modal being closed was destroyed (via. something like a state var like showModal  being set to false…and toggling its react rendering) before the close fireEvent was attempted…i.e. a timing issue.

**Comment by basham** [comment]
The problem seems to happen when you call `Modal.close()` before `Modal.open()`. In this case, the internal `activeModal` variable is undefined or null. And `fireCustomEvent()` assumes that the element passed to it exists. Yes, we should do some clean up on our code to ensure that the ordering is proper, but Rivet should also do some simple checks to prevent this error.

**Comment by levimcg** [comment]
Hey, @rileymg & @basham 

I'll label this as a bug, and we can get it prioritized for a patch release. In the meantime, if there's anyway you could create a reduced test case (a codepen, or whatever) that would be super helpful. Just so we can make sure that we're solving the problem you're running into here. Thank you! 🙌🏻 

cc: @scottanthonymurray

**Comment by basham** [comment]
Here's a CodePen that showcases the bug. Click on the "Close modal" button before clicking the "Open modal" button to see the error. I would imagine just silently ignoring the `Modal.close()` call or at least doing a check for the element before executing `fireCustomEvent()` would be a fine solutions.
https://codepen.io/basham/pen/VwmJmEV

**Comment by levimcg** [comment]
Perfect, thanks for this! 🙌🏻
