### ISSUE TITLE
Update to Gulp 4.0

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#51]
I'd like to get Gulp updated to 4.0. 4.0 was a pretty major/breaking update to Gulp so it will require rewriting and/or refactoring a lot of the tasks we have written. Most notable is that you can now choose to run tasks in [series](https://gulpjs.com/docs/en/api/series) or [parallel](https://gulpjs.com/docs/en/api/parallel) which is a pretty big change.

https://gulpjs.com/docs/en/getting-started/quick-start

**Comment by nbannist** [comment]
I think > 95% of it is converting to using the series/parallel methods from the array of tasks used in previous versions. I'm using in for the new kb styles.
