### ISSUE TITLE
Hosted Rivet 1.8.2 doesn't work - 404 error

### ISSUE THREAD

**Issue by ebigalee** [indiana-university/rivet-source#527]
## Describe the bug
I'm trying to add Rivet as a resource for the Informatics core courses and Capstone, and the hosted resource doesn't work. The 1.8.1 works fine, but it's extremely awkward to say use the hosted resource at the moment. We could have them download, but it would be less easy for us and students to maintain and for them to use.

## Expected behavior
I expect the latest version to work.

## Relevant context (required)
- DOESN'T WORK: view-source:https://assets.uits.iu.edu/css/rivet/1.8.2/rivet.min.css
- DOES WORK: view-source:https://assets.uits.iu.edu/css/rivet/1.8.1/rivet.min.css
- Documentation says it's safe to use 1.8.2
- Also, what's with using Normalize 3.x??? -- it's up to 8.x and has been for ages

## Steps to reproduce
1. Open view-source:https://assets.uits.iu.edu/css/rivet/1.8.2/rivet.min.css and see the 404
2. Open view-source:https://assets.uits.iu.edu/css/rivet/1.8.1/rivet.min.css and see it work
3. Documentation on https://rivet.iu.edu/components/ says it's safe to use 1.8.2, as do alerts and change log

Please get back to me ASAP - we are running this in classes NOW. Thanks for your help.

**Comment by levimcg** [comment]
@ebigalee Thanks for raising this issue. It looks like there was a hiccup in our deployment process last week when we release 1.8.2. I apologize for the inconvenience and we'll get it fixed up as soon as possible.

It will be first thing tomorrow/Monday morning before we can get the 1.8.2 hosted assets in place, but if the lack of assets.iu.edu hosted assets is keeping you from being able to work on a project using 1.8.2 today, you can use an alternate hosted version of the the assets until we get the main version fixed up tomorrow.

CSS:
https://unpkg.com/rivet-uits@1.8.2/css/rivet.min.css

JavaScript:
https://unpkg.com/rivet-uits@1.8.2/js/rivet.min.js

These versions are automatically generated when we publish to npm and can be used as a temporary backup until we get the 1.8.2 in place at the normal assets.iu.edu URL.

I'll follow up tomorrow first thing once we have the 1.8.2 hosted assets in place.

**Comment by ebigalee** [comment]
Thank you for the quick response! And Monday is soon enough. No problem. 

  Erika Lee

**Comment by levimcg** [comment]
@ebigalee These hosted assets are in place now and should be working as described on the documentation site.
