### ISSUE TITLE
Loading indicator button color

### ISSUE THREAD

**Issue by thrclark** [indiana-university/rivet-source#54]
Question about colors used in the Rivet loading indicator buttons...the default disabled button coloring is grey, but in the 'loading indicator' state it's blue (even though 'loading' is also a disabled state):

<img width="174" alt="screen shot 2019-01-29 at 12 33 16 pm" src="https://user-images.githubusercontent.com/5652113/51929216-ad07a680-23c5-11e9-8508-341da39b83f9.png">

It's possible that a button's previous color (before the 'loading' styles are applied) could be red, green, or blue. In which case, would it seem more reasonable to use the neutral grey coloring instead of blue?

**Comment by illusivesunrae** [comment]
Merged into master in PR #207.
