### ISSUE TITLE
Loading Indicator in button fails to hide Button icon, if the latter is present.

### ISSUE THREAD

**Issue by mtwagner** [indiana-university/rivet-source#58]
Give a button with a button with icon and a loading indicator, when class `rvt-button--loading` is applied the button behaves normally, but the icon remains. Should it be the case that the user (developer) needs to hide the icon when `rvt-button--loading` is added to the button, or is this a missing feature/functionality? 

![image](https://user-images.githubusercontent.com/1319542/52067178-0b5c9280-2548-11e9-8647-16dbf9ebd6fe.png)

**Comment by illusivesunrae** [comment]
Hey @mtwagner,
I just took a look, and it seems like if you wrap the svg in `<span class="rvt-button__text"></span>`, this should work as intended. We realize though that the `.rvt-button__text` class name may have given the impression that it wasn't for svgs and other non-text content, so we will be updating the css class name to be more descriptive. Our next release will add the `.rvt-button__content` class, and deprecate the `.rvt-button__text` class. Thanks for your contribution! 🙂
