### ISSUE TITLE
Dropdown component fails to place focus on first (or last) menu item on opening as required per ARIA practices

### ISSUE THREAD

**Issue by brichwin** [indiana-university/rivet-source#597]
## Describe the bug
The Dropdown component purports to follow the [ARIA Menu Button design pattern](https://w3c.github.io/aria-practices/#menubutton). The Rivet dropdown component is not using the aria-activedescendant attribute, so should be managing focus using element.focus(), but it fails to do so. The ARIA Practices states:
>With focus on the button:
>- Enter: opens the menu and places focus on the first menu item.
>- Space: Opens the menu and places focus on the first menu item.
>- (Optional) Down Arrow: opens the menu and moves focus to the first menu item.
>- (Optional) Up Arrow: opens the menu and moves focus to the last menu item.

This issue is an accessibility issue that affects keyboard only users and screen-reading software users.

This is important non-visual screen-reader users especially, because they will not hear any change upon activating the dropdown as the Rivet dropdown is currently coded. If focus was moved, then they would hear that the menu reacted to them and automatically be placed on the first menu item.

## Expected behavior
- When a Rivet dropdown menu opens by the Enter key, the space bar, a down arrow, or a click the dropdown's menu should appear and **focus should move to the first menu item** in that menu. 

## Relevant context (required)
- Please see the [Actions Menu Button Example Using element.focus()](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions.html) on the W3C.github.io/aria-practices site for a working example that meets the mental model Assistive Technology and keyboard only users will be expecting.
- For a failing example, please see [Rivet 1.8.2 Dropdown example](https://rivet.iu.edu/components/navigation/dropdown/#dropdown-example)
- In case it helps, here is a Kaltura [video demonstrating the key difference between the above two examples](https://iu.mediaspace.kaltura.com/media/t/1_2sqjlce3)

## Steps to reproduce

1. Navigate to [Rivet 1.8.2 Dropdown example](https://rivet.iu.edu/components/navigation/dropdown/#dropdown-example)
2. Move keyboard focus to the "Navigation menu" dropdown button
3. Press one of [enter, space, down arrow]
4. Note that focus remains on the "Navigation menu" button instead of moving to the first menu item.

**Comment by brichwin** [comment]
This issue is present in Rivet 1 and Rivet 2. Since the issue was discovered by a Canvas user, please address the Rivet 1 codebase as well.

**Comment by levimcg** [comment]
This issue was addressed in #627 and is available in the [rivet-uits@1.8.3 release](https://github.com/indiana-university/rivet-source/releases/tag/v1.8.3)
