### ISSUE TITLE
Event target being removed as a result of the click event causes dialog to close

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#632]
## Describe the bug

Say you have a list of items and each item has some text and a "remove" button that when clicked removes that list item from the list, including the click event target (button) itself.

When the click event target itself is removed the logic that checks for clicks inside of the dialog is not longer satisfied because the event listener doesn't catch the click until the AFTER the event target is gone/removed from the DOM. This causes the dialog to close because as far as it's concerned, the click came from outside of the dialog element.

## Expected behavior

Dialog should remain open no matter what happens to the click event target unless explicitly closed programmatically by the developer.

## Relevant context (required)

- Reduced test case: https://codepen.io/levimcg/pen/BaxBMrZ
- There is a not in the pen (in the JS comments) about a workaround. It is possible to work around the issue in your own application logic by wrapping any calls to remove the click event target in a `setTimeout`, but this will most likely need to be fixed in the dialog's click event listener logic.

## Steps to reproduce

1. Click button to open dialog
1. Click any of the "Remove" buttons in the dialog body
1. Dialog closes, but should stay open after list item is removed from the DOM

**Comment by scottanthonymurray** [comment]
Fixed by #633
