### ISSUE TITLE
"Skip to Main Content" link on Rivet.iu.edu does not skip navigation

### ISSUE THREAD

**Issue by brichwin** [indiana-university/rivet-source#635]
## Describe the bug
Activating the Skip to Main Content link on documentation pages does not move focus to the page's actual main content. 

## Expected behavior
Activating the Skip to Main Content link both scrolls the page to make the main content visible and moves focus into the main content. After activating the Skip to Main Content link, the user should not have to tab through the sight navigation links.

## Steps to reproduce

1. Navigate to: https://rivet.iu.edu/components/alert/
1. Press the tab key until the "Skip to Main Content" link becomes visible (and has focus) in the upper left corner of the page.
1. Press "Enter" to activate the Skip to Main Content link
2. Press the tab key again and note where focus goes on the page.
      - Focus should go to a control in the Alert content (the overview link)
      - However, focus goes to the "Getting started" link under the "Documentation" side-nav label. 

## Probable cause
The main element / main landmark should contain the page's main content. Users expect to find the main content by skipping to the page's main landmark. The first item inside the main landmark should not be a lengthy navigation region.

**Comment by scottanthonymurray** [comment]
This has been fixed in the latest release of the documentation site. Thank you!
