### ISSUE TITLE
Visibility utilities break when used for table cells

### ISSUE THREAD

**Issue by clintondrm** [indiana-university/rivet-source#645]
## Describe the bug
The utilities to show/hide elements at different breakpoints use display:hidden or display:block !important. This doesn't work elements that use table-cell as their display default.

## Expected behavior
For elements matching table th.rvt-hide-md-down or table td.rvt-hide-md-down (for example), I would suggest using display:table-cell instead of block.

## Relevant context (required)
See demo: [https://codepen.io/cldmckay/full/rNvKjqE](https://codepen.io/cldmckay/full/rNvKjqE)

## Steps to reproduce

1. Add a visibility class to a <th> element and the corresponding <td> elements within a table
2. View above and below the relevant break point. 
3. Note that display is set to block, but the default for these elements is table-cell

**Comment by scottanthonymurray** [comment]
Fixed in `2.3.1`.
