### ISSUE TITLE
CSS issues in header

### ISSUE THREAD

**Issue by conhay-ovpue** [indiana-university/rivet-source#651]
Hello I am a app developer for IU OVPUE. I have noticed in the rivet 2 header there is two aesthetic issues at my boss wanted me to report.

The first issue:
![Underline extends to the right](https://user-images.githubusercontent.com/116106278/196500993-3b8215cb-b309-44fd-bdba-135f57289bb8.PNG)
Here the underline on the currently selected tab goes to far to the right.

The second issue:
![No space at bottom of drop down](https://user-images.githubusercontent.com/116106278/196501124-dd4c294e-21ed-4417-a77b-18132457d2b5.PNG)
Here there is no padding at the end of the dropdown. I noticed that this is not the case until the screen width is greater than 740.

These are not urgent fixes.

Thanks,
Connor Hay

**Comment by scottanthonymurray** [comment]
Fixed in `2.3.1`.
