### ISSUE TITLE
Native browser buttons have 1px padding top 2px padding bottom

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#71]
**Problem:**
`<button class="rvt-button" />` has a 1px top padding and 2px bottom padding. `<a class="rvt-button" />` has none.

**Screenshot:**
<img width="549" alt="screen shot 2019-02-19 at 11 32 29 am" src="https://user-images.githubusercontent.com/1017119/53038472-15343000-343a-11e9-89ec-884193592d6e.png">

**Demonstration:**
![button-padding](https://user-images.githubusercontent.com/1017119/53038661-8673e300-343a-11e9-9dbd-327e03098872.gif)

**Comment by levimcg** [comment]
Closed via #72
