### ISSUE TITLE
Add utility classes to remove left/right and top/bottom spacing

### ISSUE THREAD

**Issue by jameswilson** [indiana-university/rivet-source#733]
## Describe the bug

There are no utility classes to zero out top/bottom or left/right spacing at all breakpoints. (For this example, we'll use padding but the same could be said for margin.)

The nearest available approaches currently include:
* the `rvt-p-all-none` which overzealously affects both top/bottom and left/right spacing, and thus requires adding back top/bottom padding with `rvt-p-tb-sm`.
* the `rvt-p-lr-none-sm-up` and similar, which do not account for smallest screens (i.e. less than 30em wide) and therefore ends up with double-padding at the smallest screen sizes where whitespace is at a premium.

Documentation for [Adding utility classes to existing component markup][Extending Rivet] states the following; **emphasis** is mine:

> **Aside from spacing and width**, you should avoid using utilities to change the appearance of built-in components when possible.

## Expected behavior

Be able to remove the inherent left/right or top/bottom whitespace provided by a Rivet component by adding a single class. E.g., `[ rvt-p-lr-none ]`. 

## Relevant context (required)

Example:
A [Rivet Alert banner][] for Campus/Site-wide Notice.

Double padding of Rivet Alert on small screens:
<img width="452" alt="Double padding of Rivet Alert on small screens" src="https://github.com/indiana-university/rivet-source/assets/243532/730e3184-0b20-4ac0-8ebb-b8f4de81648d">

Fix for double padding:
<img width="1221" alt="Fix for double padding" src="https://github.com/indiana-university/rivet-source/assets/243532/60f6b49c-7e29-4d2c-bbca-c370a3544b79">

## Steps to reproduce

1. Implement any component that contains default left/right padding, e.g. the [Rivet Alert][] component.
2. Remove the default whitespace by adding `[ rvt-p-lr-none-sm-up ]`.
3. Add back necessary whitespace via another mechanism on a different element. E.g. Inside the component's top-level div, add a `<div class="rvt-container-xl">`.
4. Resize viewport to less than 30em.

[Extending Rivet]: https://rivet.iu.edu/getting-started/extending-rivet/#adding-utility-classes-to-existing-component-markup
[Rivet Alert]: https://rivet.iu.edu/components/alert/
[Rivet Alert banner]: https://codepen.io/jameswilson/pen/WNPdObZ

**Comment by scottanthonymurray** [comment]
Fixed in `2.6.0`
