### ISSUE TITLE
Ascenders & descenders in Rivet Select input are cutoff in Webkit

### ISSUE THREAD

**Issue by jameswilson** [indiana-university/rivet-source#734]
## Describe the bug
The Rivet [Select input](https://rivet.iu.edu/components/select-input/?example=default-select-input) element has `line-height: 1` which cuts off lowercase letters of the alphabet with descenders such as `g`, `y`, `j`, and cuts off uppercase letters with ascenders such as `À`, and `Ĥ` in Chrome and Safari browsers.

## Expected behavior
The Select input element should have a `line-height: normal` to ensure ascenders and descenders are not cut off in Webkit browsers.

## Relevant context (required)

- Mac OS Monterrey 12.7.1
- Google Chrome version 119.0.6045.159 (x86_64)
- Safari Version 17.1 (17616.2.9.11.9, 17616)
- _Firefox did not exhibit this bug_
- _Normal text inputs and textareas are not affected_
- https://codepen.io/jameswilson/pen/OJdoyNo

Chrome:
<img width="559" alt="Screen Shot 2023-11-28 at 3 17 50 PM" src="https://github.com/indiana-university/rivet-source/assets/243532/1a7f5b41-5aaa-4222-9b5b-013eaee25eb2">

Safari: (Descenders are less evident, but still affected)
<img width="562" alt="Screen Shot 2023-11-28 at 3 18 26 PM" src="https://github.com/indiana-university/rivet-source/assets/243532/3abde473-fac1-41e6-9198-93553dccc004">

**Comment by scottanthonymurray** [comment]
Fixed in `2.6.0`
