### ISSUE TITLE
Duplicate fill attribute in base footer trident

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#739]
The trident SVG in the base footer has two `fill` attributes—one with a value of `currentColor` and one with a value of `#231f20`.

@levimcg Which one should be snipped out?

**Comment by levimcg** [comment]
@scottanthonymurray Oh yeah, I see that now. Yeah, we should just use `fill=currentColor`. We are using CSS already to apply the white color to it.

**Comment by levimcg** [comment]
This is all fixed up in [on the docs site](https://rivet.iu.edu/components/footer/) now.
