### ISSUE TITLE
Switch with data-rvt-switch-on triggers rvtSwitchToggledOn event on page load. 

### ISSUE THREAD

**Issue by mtwagneratiu** [indiana-university/rivet-source#742]
When using the rvtSwitchToggledOn event to save settings to a backend datastore, applying the data-rvt-switched-on attribute to a switch element on page load to show the current state of the switch, causes the rvtSwitchToggledOn event to fire on every page load. This can cause a saved modifiedDttm to be updated on every page load rather than with the switch is actually changed. 

Is it possible to set the state of a switch without the need for firing the rvtSwitchToggledOn event? For example; manually setting the aria-checked attribute to true, should be enough to visually initiate the switched in the "On" state.

**Comment by levimcg** [comment]
@mtwagneratiu Hmmmm, as it is now, no you can only set the state (both internal JavaScript, and the DOM) of the switch programmatically via the `switchOn()` method which in turn fires the `rvtSwitchToggledOn`. So there is know way to set the state programmatically and stop the event from firing.

This is the first time we've run into this, so I'll dig a bit deeper and talk with the team. There may be a way to change how we're setting up the state of the switch when using the `data-rvt-switch-on` attribute that doesn't use the built-in `switchOn()` method, but it would have to be via a patch release.

**Comment by mtwagneratiu** [comment]
While a bit kludgey, I manage to use this as a workaround. 

```
document.addEventListener('rvtSwitchToggledOn', function (event) {
    if (event.target.hasAttribute("data-rvt-switch-on")) {
        event.target.removeAttribute("data-rvt-switch-on")
    } else {
        ...
    }
})
```

**Comment by levimcg** [comment]
We should have a fix in place for this behavior as of the recent 2.7.0 release 👉🏻 #748.
