### ISSUE TITLE
Pie chart

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#84]
Pie chart to visualize a percentage

![screen shot 2019-03-01 at 1 19 06 pm](https://user-images.githubusercontent.com/1017119/53664046-9d79b880-3c24-11e9-897b-614847649b29.png)

**Comment by levimcg** [comment]
@jolamar When you get a chance can you provide a little more info about how you're currently using pie charts (or any data viz for that matter)?

I'm interested to see how many folks that are using Rivet are also doing some sort of custom data visualization. For example, which JS libraries (d3, chart.js, etc.) are you using? Are you customizing the colors or to match Rivet colors? What type of work are you doing to make your data viz. accessible e.g. a duplicate text-only version.

**Comment by basham** [comment]
The only data visualization efforts that I'm aware of in ESS is in regards to a desire to put such things in the AdRx Landing Page. Nothing has been done. We're still trying to decide what data to use, so we're far from knowing which visualizations and technology to couple that with.
