### ISSUE TITLE
Decouple Javascript and CSS class names

### ISSUE THREAD

**Issue by jolamar** [indiana-university/rivet-source#85]
Sometimes I may want to have a button styled a specific way (e.g. a dismiss button) but not have it be triggered by rivet.js. I propose adding an additional class for javascript such as `.rvt-alert__dismiss--js-trigger`

https://github.com/indiana-university/rivet-source/blob/develop/src/js/components/alert.js#L50

This is mainly a problem for Vue and React where the alert may not be in the DOM after clicking the button because it's removed by Vue/React.

**Comment by basham** [comment]
+1 for decoupling.

What other components are coupled like Alerts? It may be good to try to do an audit and establish some standard for the hooks, if using class names or data attributes or something else.

**Comment by levimcg** [comment]
@jolamar Good call. I _think_ we've mostly decoupled JS functionality from any CSS selectors everywhere else. They all should use data attribute/id combos for that. The alert just got overlooked. 

We should be able to do this in a backward-compatible way like we did in the tabs component with `aria-controls`.
