### ISSUE TITLE
Header drawer missing bottom border in specific case

### ISSUE THREAD

**Issue by scottanthonymurray** [indiana-university/rivet-source#9]
The style on the `rvt-header-id__profile--drawer` class is missing a bottom border to make its styling consistent with the other items in the header drawer.  This results in the header drawer looking like the following:
![image](https://media.github.iu.edu/user/2029/files/095316ce-b8e9-11e8-972a-c5f2c1dfb2ac)

I believe the fix would be to add `border-bottom: 2px solid $color-black--100;` to the `rvt-header-id__profile--drawer` class but it might need more testing.

**Comment by illusivesunrae** [comment]
Merged into master in PR #207.
