### ISSUE TITLE
Missing license - _utilities-flex.scss

### ISSUE THREAD

**Issue by nbannist** [indiana-university/rivet-source#90]
## Describe the bug
License is missing at the top of `/src/sass/utilities/_utilities-flex.scss`

## Expected behavior
That it has a license in single line comments at the top of the file like other scss files.

## Relevant context (required)
https://github.com/indiana-university/rivet-source/blob/develop/src/sass/utilities/_utilities-flex.scss

## Steps to reproduce
Click the link above.

**Comment by levimcg** [comment]
@illusivesunrae Just a heads-up. I pulled this one in and put you on it. This'll be a super quick one, but needs to go out in the next release. 👍
