### ISSUE TITLE
Footer content wrapping on small screens

### ISSUE THREAD

**Issue by thrclark** [indiana-university/rivet-source#96]
The newly refactored footer doesn't wrap content gracefully on smaller screens. Examples below are at 320px wide:

![footer](https://user-images.githubusercontent.com/5652113/54680857-4b200f00-4ae1-11e9-8ba2-162e4eef9f2a.png)

Live demo of suggested layout:
http://www.indiana.edu/~espd/rvb/develop/php/lib-footer.php

**Comment by illusivesunrae** [comment]
Merged into master with #110.
